config/routes.rb
Rails.application.routes.draw do
  resources :pastes
  get 'static_pages/index'

  get 'static_pages/about'
  root 'static_pages#index'

end

app/models/paste.rb
class Paste < ActiveRecord::Base
  before_create :generate_slug

  private
  def generate_slug
    self.slug = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pastes_controller.rb
class PastesController < ApplicationController
  before_action :set_paste, only: [:show, :edit, :update, :destroy]

  # GET /pastes
  # GET /pastes.json
  def index
    @paste = Paste.new
    render :new
  end

  # GET /pastes/1
  # GET /pastes/1.json
  def show
  end

  # GET /pastes/new
  def new
    @paste = Paste.new
  end

  # GET /pastes/1/edit
  def edit
  end

  # POST /pastes
  # POST /pastes.json
  def create
    @paste = Paste.new(paste_params)
    respond_to do |format|
      if @paste.save
        format.html { redirect_to paste_path(id: @paste.slug), notice: 'Paste was successfully created.' }
        format.json { render :show, status: :created, location: @paste }
      else
        format.html { render :new }
        format.json { render json: @paste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pastes/1
  # PATCH/PUT /pastes/1.json
  def update
    respond_to do |format|
      if @paste.update(paste_params)
        format.html { redirect_to @paste, notice: 'Paste was successfully updated.' }
        format.json { render :show, status: :ok, location: @paste }
      else
        format.html { render :edit }
        format.json { render json: @paste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastes/1
  # DELETE /pastes/1.json
  def destroy
    @paste.destroy
    respond_to do |format|
      format.html { redirect_to pastes_url, notice: 'Paste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paste
      @paste = Paste.find_by(slug: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paste_params
      params.require(:paste).permit(:title, :code, :slug)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pastes_helper.rb
module PastesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crux</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
        <a class="navbar-brand" href="#">Crux</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav navbar-nav">
            <li class="active"><a href="#">Make Me Link to Paste</a></li>
            <li><a href="http://tiffzhang.com/startup/index.html?s=454565081279">About Youscribble</a></li>
        </ul>
    </div>
    </nav>
    <div class="container">
    <%= yield %>
    </div>      
    <footer>
    <p>&copy; Youscribble</p>
    </footer>
</body>
</html>

app/views/pastes/_form.html.erb
    <div class="row">
    <div class="col-lg-12">
    <% if @paste.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@paste.errors.count, "error") %> prohibited this paste from being saved:</h2>
        <ul>
        <% @paste.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>
    </div>
    </div>
    <div class="row">
    <%= form_for(@paste, :html => {class: "form-horizontal"}) do |f| %>
    <fieldset>
        <legend>New Crux</legend>
    <div class="form-group">
        <%= f.label :title, class: "col-lg-2 control-label" %><br>
        <div class="col-lg-10">
        <%= f.text_field :title, class: "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :code, class: "col-lg-2 control-label" %><br>
        <div class="col-lg-10">
        <%= f.text_area :code, class: "form-control", rows: 22 %>
        </div>
    </div>
    <div class="form-group">
        <%= f.submit %>
    </div>
    </fieldset>
    <% end %>
    </div>

app/views/pastes/edit.html.erb
<h1>Editing Paste</h1>

<%= render 'form' %>

<%= link_to 'Show', @paste %> |
<%= link_to 'Back', pastes_path %>

app/views/pastes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pastes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Code</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pastes.each do |paste| %>
      <tr>
        <td><%= paste.title %></td>
        <td><%= paste.code %></td>
        <td><%= paste.slug %></td>
        <td><%= link_to 'Show', paste %></td>
        <td><%= link_to 'Edit', edit_paste_path(paste) %></td>
        <td><%= link_to 'Destroy', paste, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paste', new_paste_path %>

app/views/pastes/new.html.erb
<%= render 'form' %>

app/views/pastes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @paste.title %></strong>
</p>

<p>
  <pre>
    <%= @paste.code %>
  </pre>
</p>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/index.html.erb
<div class="row">
      <div class="jumbotron">
        <h1>Crux</h1>
        <p>Paste your stuffs</p>
        <p><a class="btn btn-primary btn-lg">Learn more</a></p>
      </div>
    </div>